apiVersion: v1
data:
  init-airflow.sh: |
    set -e
    export USER_ID=$(id -u)
    export GROUP_ID=$(id -g)
    export AIRFLOW_HOME=${AIRFLOW_HOME}
    export AIRFLOW_CONFIG=${AIRFLOW_HOME}/airflow.cfg
    echo "${USER_NAME:-default}:x:$(id -u):0:${USER_NAME:-default} user:${HOME}:/sbin/nologin" >> /etc/passwd

    AIRFLOW_PATH=`pip3 show apache-airflow | grep 'Location: ' | cut -d' ' -f2 || true`
      if [ -z $AIRFLOW_PY3 ]; then
         AIRFLOW_PATH=`pip show apache-airflow | grep 'Location: ' | cut -d' ' -f2`
      fi
      AIRFLOW_VERSION=`pip freeze | grep apache-airflow | cut -d'=' -f3`
    cd $AIRFLOW_PATH/airflow
    airflow upgradedb
    alembic upgrade heads

    if [[ "$AIRFLOW_VERSION" > "2" ]]; then
    CREATE_USER="users --create"
    else
    CREATE_USER="create_user"
    fi
kind: ConfigMap
metadata:
  labels:
    app: airflow
  name: airflow-init
