apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb
  labels:
    app: airflow
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/mysql-data"
